name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_dir:
          - packages/dom-to-canvas
          - packages/dom-to-canvas-react
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bunx jsr publish
        working-directory: ${{ matrix.package_dir }}
